using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Programming
{
    /// <summary>
    /// Создано для генерации названия фильма. Возможно только получить значение типа string через <see cref="GetMovieName"></see>
    /// </summary>
    class MovieNames
    {
        private string[] _movieFirsNames = ["Beautiful",
            "Kind",
            "Smart",
            "Strong",
            "Funny",
            "Honest",
            "Generous",
            "Loyal",
            "Creative",
            "Caring",
            "Brave",
            "Gentle",
            "Stylish",
            "Charming",
            "Sincere",
            "Adventurous",
            "Ambitious",
            "Cheerful",
            "Determined",
            "Gracious",
            "Optimistic",
            "Witty",
            "Empathetic",
            "Independent",
            "Resilient",
            "Courageous",
            "Lovable",
            "Curious",
            "Affectionate",
            "Thoughtful",
            "Reliable",
            "Energetic",
            "Polite",
            "Passionate",
            "Confident",
            "Humble",
            "Sophisticated",
            "Unique",
            "Vibrant",
            "Mature",
            "Peaceful",
            "Resourceful",
            "Radiant",
            "Genuine",
            "Sensible",
            "Innovative",
            "Enthusiastic",
            "Charismatic",
            "Graceful",
            "Adaptable",
            "Trustworthy",
            "Outgoing",
            "Harmonious",
            "Exuberant",
            "Empowering",
            "Knowledgeable",
            "Versatile",
            "Decisive",
            "Brilliant",
            "Compassionate",
            "Warmhearted",
            "Fascinating",
            "Inspiring",
            "Courteous",
            "Joyful",
            "Talented",
            "Dynamic",
            "Elegant",
            "Persistent",
            "Balanced",
            "Skilful",
            "Tolerant",
            "Insightful",
            "Diligent",
            "Adventurous",
            "Wholesome",
            "Motivated",
            "Sociable",
            "Inventive",
            "Gregarious",
            "Inquisitive",
            "Philosophical",
            "Forgiving",
            "Analytical",
            "Punctual",
            "Affable",
            "Knowledgeable",
            "Reasonable",
            "Gallant",
            "Innovative",
            "Conscientious",
            "Hard-working",
            "Dedicated",
            "Cooperative",
            "Lively",
            "Welcoming",
            "Understanding",
            "Perceptive",
            "Considerate",
            "Devoted"];
        private string[] _movieSecondNames = ["Apple",
            "Banana",
            "Cat",
            "Dog",
            "Elephant",
            "Fish",
            "Giraffe",
            "Horse",
            "Ice cream",
            "Jacket",
            "Kite",
            "Lion",
            "Moon",
            "Nest",
            "Orange",
            "Pencil",
            "Queen",
            "Rabbit",
            "Sun",
            "Table",
            "Umbrella",
            "Violin",
            "Water",
            "Xylophone",
            "Yacht",
            "Zebra",
            "Airplane",
            "Book",
            "Chair",
            "Dolphin",
            "Egg",
            "Frog",
            "Guitar",
            "Hat",
            "Ink",
            "Jellyfish",
            "Kangaroo",
            "Lemon",
            "Map",
            "Notebook",
            "Owl",
            "Penguin",
            "Quilt",
            "Rainbow",
            "Socks",
            "Telescope",
            "Unicorn",
            "Vase",
            "Wallet",
            "X-ray",
            "Yogurt",
            "Zipper",
            "Ant",
            "Beach",
            "Cloud",
            "Diamond",
            "Earrings",
            "Fire",
            "Globe",
            "Hamburger",
            "Ice",
            "Jigsaw puzzle",
            "Kettle",
            "Lamp",
            "Mountain",
            "Note",
            "Oasis",
            "Piano",
            "Quarter",
            "Rose",
            "Sunglasses",
            "Train",
            "Ukulele",
            "Violin",
            "Wallet",
            "Xylophone",
            "Yacht",
            "Zoo",
            "Apricot",
            "Bicycle",
            "Cactus",
            "Daisy",
            "Eclipse",
            "Flamingo",
            "Garden",
            "Hammer",
            "Iceberg",
            "Jewelry",
            "Kiwi",
            "Laptop",
            "Mango",
            "Newspaper",
            "Orchid",
            "Parrot",
            "Quartz",
            "Rug",
            "Sandcastle",
            "Teapot",
            "Umbrella",
            "Violet"];
        Random rand = new Random();

        /// <summary>
        /// Получить случайное название для фильма.
        /// </summary>
        /// <returns></returns>
        public string GetMovieName()
        {
            int firstRand = rand.Next(100);
            int secondRand = rand.Next(100);
            string movieName = _movieFirsNames[firstRand].ToString() + " " + _movieSecondNames[secondRand].ToString();
            return movieName;
        }
        public MovieNames() { }
    }
}
